name: aerospike-client-go
dir: src/github.com/archsaber/aerospike-client-goo

container:
  - base:
      - docker.qe.aerospike.com/build/aerospike-client-go:golang-1.5
      - docker.qe.aerospike.com/build/aerospike-client-go:golang-1.6

build:
  - name: build
    script:
      - go get -v github.com/archsaber/aerospike-client-goo
      - go build -v -x github.com/archsaber/aerospike-client-goo
      - go install -v -x github.com/archsaber/aerospike-client-goo/tools/cli
      - go install -v -x github.com/archsaber/aerospike-client-goo/tools/benchmark
      - go install -v -x github.com/archsaber/aerospike-client-goo/tools/asinfo
